apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example
spec:
  selector:
    app: example
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 8080
