name: Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  deployment:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: syntaqx/setup-kustomize@v1
      -
        name: Deploy
        working-dir: k8s/overlays/production
        run: |-
          kustomize edit set image syntaqx/example=syntaqx/example:sha-12345
          kustomize build .
